## 08-06-2026 DATA MANIPULATION

In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
titanic = pd.read_csv(r"/content/titanic_sample_100.csv")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Theresa Davis,male,37.0,2,1,39256,75.88,B20,Q
1,2,0,3,Jose Clark,male,28.1,3,0,13905,63.88,E46,S
2,3,0,3,Laura Mccarthy PhD,male,26.7,1,5,95181,15.23,G6,S
3,4,1,1,Phillip Merritt,female,26.7,1,5,65392,87.96,F2,C
4,5,0,2,Tina Mercado,male,52.1,0,0,59797,11.85,E46,C
...,...,...,...,...,...,...,...,...,...,...,...,...
145,146,1,3,Sylvia Skinner,male,28.4,5,5,99241,96.64,B20,Q
146,147,0,2,Jimmy Hernandez,male,37.1,3,0,85965,46.81,F2,Q
147,148,0,2,Stephanie Scott,male,42.1,2,5,64460,25.60,B20,S
148,149,1,3,Jennifer Ortega,male,23.4,4,2,31567,59.43,A10,C
149,150,1,1,Joseph Johnson,female,20.9,3,0,28449,74.31,D33,Q

In [3]:
titanic.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Theresa Davis,male,37.0,2,1,39256,75.88,B20,Q
1,2,0,3,Jose Clark,male,28.1,3,0,13905,63.88,E46,S
2,3,0,3,Laura Mccarthy PhD,male,26.7,1,5,95181,15.23,G6,S
3,4,1,1,Phillip Merritt,female,26.7,1,5,65392,87.96,F2,C
4,5,0,2,Tina Mercado,male,52.1,0,0,59797,11.85,E46,C
5,6,1,1,Dale Finley,female,40.7,5,3,80284,97.29,E46,C
6,7,1,3,Savannah Schmidt,male,23.4,4,2,85674,26.36,D33,Q
7,8,0,3,Lisa Acosta,male,37.6,1,2,20458,26.51,D33,S
8,9,1,2,Lisa Tucker,female,33.4,5,2,31319,48.88,F2,C
9,10,1,3,Cody Cox,male,3.2,5,5,19358,36.21,B20,Q

In [4]:
titanic.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
140,141,1,2,Michael Mccormick,male,30.6,5,4,30706,58.66,E46,C
141,142,1,3,Gregory Collins,female,20.9,3,5,42780,67.37,NaN,C
142,143,1,2,Samantha Ellis,male,1.6,0,1,59986,81.57,F2,Q
143,144,1,1,Laurie Rice,female,32.6,5,3,45976,34.37,C123,Q
144,145,1,2,Ronald Davis,male,18.9,1,4,56179,12.28,D33,Q
145,146,1,3,Sylvia Skinner,male,28.4,5,5,99241,96.64,B20,Q
146,147,0,2,Jimmy Hernandez,male,37.1,3,0,85965,46.81,F2,Q
147,148,0,2,Stephanie Scott,male,42.1,2,5,64460,25.60,B20,S
148,149,1,3,Jennifer Ortega,male,23.4,4,2,31567,59.43,A10,C
149,150,1,1,Joseph Johnson,female,20.9,3,0,28449,74.31,D33,Q

In [6]:
# data types of all columns
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket           int64
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [8]:
titanic.dtypes == "object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [9]:
titanic.dtypes[titanic.dtypes == "object"]

Name        object
Sex         object
Cabin       object
Embarked    object
dtype: object

In [10]:
# Describes how the data is distributed.
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Ticket,Fare
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.00000,150.000000,150.000000
mean,75.500000,0.520000,1.980000,30.395333,2.766667,2.60000,55969.200000,55.512800
std,43.445368,0.501274,0.831187,12.673136,1.781398,1.69484,26109.146486,27.095997
min,1.000000,0.000000,1.000000,1.600000,0.000000,0.00000,10221.000000,10.460000
25%,38.250000,0.000000,1.000000,21.725000,1.000000,1.00000,35046.000000,33.995000
50%,75.500000,1.000000,2.000000,30.700000,3.000000,3.00000,59619.000000,56.905000
75%,112.750000,1.000000,3.000000,37.275000,4.000000,4.00000,78436.000000,80.082500
max,150.000000,1.000000,3.000000,83.900000,5.000000,5.00000,99539.000000,99.100000

In [11]:
# displays specified columns
titanic[['Name','Age','Sex']]

                   Name   Age     Sex
0         Theresa Davis  37.0    male
1            Jose Clark  28.1    male
2    Laura Mccarthy PhD  26.7    male
3       Phillip Merritt  26.7  female
4          Tina Mercado  52.1    male
..                  ...   ...     ...
145      Sylvia Skinner  28.4    male
146     Jimmy Hernandez  37.1    male
147     Stephanie Scott  42.1    male
148     Jennifer Ortega  23.4    male
149      Joseph Johnson  20.9  female

[150 rows x 3 columns]

In [12]:
# Describes a particular column
titanic['Age'].describe()

count    150.000000
mean      30.395333
std       12.673136
min        1.600000
25%       21.725000
50%       30.700000
75%       37.275000
max       83.900000
Name: Age, dtype: float64

In [13]:
# display columns of the dataframe
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [14]:
# we can add a column for the dataframe

titanic["message"]="LetsGoooo"
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,message
0,1,0,3,Theresa Davis,male,37.0,2,1,39256,75.88,B20,Q,LetsGoooo
1,2,0,3,Jose Clark,male,28.1,3,0,13905,63.88,E46,S,LetsGoooo
2,3,0,3,Laura Mccarthy PhD,male,26.7,1,5,95181,15.23,G6,S,LetsGoooo
3,4,1,1,Phillip Merritt,female,26.7,1,5,65392,87.96,F2,C,LetsGoooo
4,5,0,2,Tina Mercado,male,52.1,0,0,59797,11.85,E46,C,LetsGoooo

In [16]:
titanic["Survived"]

0      0
1      0
2      0
3      1
4      0
      ..
145    1
146    0
147    0
148    1
149    1
Name: Survived, Length: 150, dtype: int64

In [17]:
# unique - gives all the unique values from the column

titanic["Cabin"].unique()

array(['B20', 'E46', 'G6', 'F2', 'D33', 'A10', nan, 'C123'], dtype=object)

In [19]:
# isnull checks for null values
titanic.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age             0
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin          21
Embarked        0
message         0
dtype: int64

In [21]:
np.where(titanic["Age"].isnull()==True)

(array([], dtype=int64),)

In [22]:
# returns the max value of the column
titanic["Age"].max()

83.9

In [23]:
import pandas as pd
# A Series is a 1-dimensional structure.

marks = pd.Series([80,90,70,95])
marks

0    80
1    90
2    70
3    95
dtype: int64

In [26]:
# Series with Custom Index
marks = pd.Series(
    [80,90,70],
    index=["Lahari","Bharathi","Pranav"]
)
marks

Lahari      80
Bharathi    90
Pranav      70
dtype: int64

In [28]:
# Series Arithmetic
s1 = pd.Series([10,20,30], index=["A","B","C"])

s2 = pd.Series([5,15,25], index=["A","B","D"])

s1 + s2

#Pandas matches indexes automatically.

A    15.0
B    35.0
C     NaN
D     NaN
dtype: float64

In [29]:
data = {
    "Student": ["Lahari", "Pranav", "Bharathi", "Bannuru", "Srikar", "Teja", "Vinay"],
    "Math": [85, 92, 78, 95, 88, 81, 94],
    "Science": [90, 89, 85, 98, 80, 87, 92],
    "English": [95, 98, 90, 99, 92, 94, 89]
}

df = pd.DataFrame(data)

print(df)

    Student  Math  Science  English
0    Lahari    85       90       95
1    Pranav    92       89       98
2  Bharathi    78       85       90
3   Bannuru    95       98       99
4    Srikar    88       80       92
5      Teja    81       87       94
6     Vinay    94       92       89

In [30]:
df.loc[1] # Returns row with label 1.

Student    Pranav
Math           92
Science        89
English        98
Name: 1, dtype: object

In [31]:
df.iloc[1] # Returns second row.

Student    Pranav
Math           92
Science        89
English        98
Name: 1, dtype: object

In [32]:
# Adding New Columns
df["Average"] = (df["Math"] + df["Science"]) / 2

In [33]:
# Boolean Filtering : Students scoring more than 85
df[df["Math"] > 85]

   Student  Math  Science  English  Average
1   Pranav    92       89       98     90.5
3  Bannuru    95       98       99     96.5
4   Srikar    88       80       92     84.0
6    Vinay    94       92       89     93.0

In [34]:
# Multiple Conditions
df[
    (df["Math"] > 80)
    &
    (df["Science"] > 85)
]

   Student  Math  Science  English  Average
0   Lahari    85       90       95     87.5
1   Pranav    92       89       98     90.5
3  Bannuru    95       98       99     96.5
5     Teja    81       87       94     84.0
6    Vinay    94       92       89     93.0

In [35]:
# Selecting Specific Columns After Filtering
df[df["Math"] > 80][["Student","Math"]]

   Student  Math
0   Lahari    85
1   Pranav    92
3  Bannuru    95
4   Srikar    88
5     Teja    81
6    Vinay    94

In [37]:
# Reset Index : Old index becomes a new column.
df.reset_index()

   index   Student  Math  Science  English  Average
0      0    Lahari    85       90       95     87.5
1      1    Pranav    92       89       98     90.5
2      2  Bharathi    78       85       90     81.5
3      3   Bannuru    95       98       99     96.5
4      4    Srikar    88       80       92     84.0
5      5      Teja    81       87       94     84.0
6      6     Vinay    94       92       89     93.0

In [38]:
#Creates a fresh index.
df.reset_index(drop=True)

    Student  Math  Science  English  Average
0    Lahari    85       90       95     87.5
1    Pranav    92       89       98     90.5
2  Bharathi    78       85       90     81.5
3   Bannuru    95       98       99     96.5
4    Srikar    88       80       92     84.0
5      Teja    81       87       94     84.0
6     Vinay    94       92       89     93.0

In [36]:
# Set Index
df.set_index("Student")

          Math  Science  English  Average
Student
Lahari      85       90       95     87.5
Pranav      92       89       98     90.5
Bharathi    78       85       90     81.5
Bannuru     95       98       99     96.5
Srikar      88       80       92     84.0
Teja        81       87       94     84.0
Vinay       94       92       89     93.0

In [45]:
data = {
    "Student": ["Lahari", "Pranav", "Bharathi", "Bannuru", "Srikar", "Teja", "Vinay"],
    "Math": [85, 92, 78, 95, 88, 81, np.nan],
    "Science": [90, 89, 85, np.nan, 80, 87, 92],
    "English": [95, np.nan, 90, 99, 92, np.nan, 89]
}

df = pd.DataFrame(data)

print(df)

    Student  Math  Science  English
0    Lahari  85.0     90.0     95.0
1    Pranav  92.0     89.0      NaN
2  Bharathi  78.0     85.0     90.0
3   Bannuru  95.0      NaN     99.0
4    Srikar  88.0     80.0     92.0
5      Teja  81.0     87.0      NaN
6     Vinay   NaN     92.0     89.0

In [46]:
# Removes missing values, Only rows having no missing values remain.
df.dropna()

    Student  Math  Science  English
0    Lahari  85.0     90.0     95.0
2  Bharathi  78.0     85.0     90.0
4    Srikar  88.0     80.0     92.0

In [47]:
df.dropna(axis=1) # axis=1 : Means columns.

    Student
0    Lahari
1    Pranav
2  Bharathi
3   Bannuru
4    Srikar
5      Teja
6     Vinay

In [48]:
# thresh Parameter : Keep rows with minimum number of non-null values.

df.dropna(thresh=3)

    Student  Math  Science  English
0    Lahari  85.0     90.0     95.0
1    Pranav  92.0     89.0      NaN
2  Bharathi  78.0     85.0     90.0
3   Bannuru  95.0      NaN     99.0
4    Srikar  88.0     80.0     92.0
5      Teja  81.0     87.0      NaN
6     Vinay   NaN     92.0     89.0

In [49]:
# fillna() : Replace missing values.
# Fill with Constant

df.fillna("Not Available")

    Student           Math        Science        English
0    Lahari           85.0           90.0           95.0
1    Pranav           92.0           89.0  Not Available
2  Bharathi           78.0           85.0           90.0
3   Bannuru           95.0  Not Available           99.0
4    Srikar           88.0           80.0           92.0
5      Teja           81.0           87.0  Not Available
6     Vinay  Not Available           92.0           89.0

In [51]:
# Fill marks with Average marks
df["English"].fillna(
    df["English"].mean()
)

0    95.0
1    93.0
2    90.0
3    99.0
4    92.0
5    93.0
6    89.0
Name: English, dtype: float64

In [57]:
students = pd.DataFrame({
    "Student": ["Lahari", "Pranav", "Bharathi", "Bannuru", "Srikar", "Teja", "Vinay"],
    "Department": ["Math", "Biology", "Math", "English", "Math", "Biology", "English"],
    "Total_Marks": [750, 650, 820, 680, 700, 780, 840]
})

In [58]:
students.groupby("Department")

In [59]:
# Average Salary by Department

students.groupby("Department").mean(
    numeric_only=True
)

            Total_Marks
Department
Biology      715.000000
English      760.000000
Math         756.666667

In [60]:
# total salary by department

students.groupby("Department").sum(
    numeric_only=True
)

            Total_Marks
Department
Biology            1430
English            1520
Math               2270

In [61]:
team1 = pd.DataFrame({
    "student":["Lahari","Pranav", "Teja"],
    "Total_Marks":[750,650,780]
})

In [62]:
team2 = pd.DataFrame({
    "student":["Bharathi","Srikar", "Vinay", "Bannuru"],
    "Total_Marks":[820,700,840,680]
})

In [63]:
pd.concat([team1, team2])

    student  Total_Marks
0    Lahari          750
1    Pranav          650
2      Teja          780
0  Bharathi          820
1    Srikar          700
2     Vinay          840
3   Bannuru          680

In [64]:
dept = pd.DataFrame({
    "Department":["Math","Biology", "English"]
})

pd.concat([team1, dept], axis=1)

  student  Total_Marks Department
0  Lahari          750       Math
1  Pranav          650    Biology
2    Teja          780    English

In [69]:
students1 = pd.DataFrame({
    "studID":[1,2,3],
    "student":["Lahari","Pranav", "Teja"]
})

In [70]:
students2 = pd.DataFrame({
    "studID":[1,2,4],
    "Total_Marks":[750,650,780]
})

In [71]:
pd.merge(
    students1,
    students2,
    how="inner",
    on="studID"
)

   studID student  Total_Marks
0       1  Lahari          750
1       2  Pranav          650

In [73]:
pd.merge(
    students1,
    students2,
    how="left",
    on="studID"
)

   studID student  Total_Marks
0       1  Lahari        750.0
1       2  Pranav        650.0
2       3    Teja          NaN

In [74]:
pd.merge(
    students1,
    students2,
    how="right",
    on="studID"
)

   studID student  Total_Marks
0       1  Lahari          750
1       2  Pranav          650
2       4     NaN          780

In [75]:
pd.merge(
    students1,
    students2,
    how="outer",
    on="studID"
)

   studID student  Total_Marks
0       1  Lahari        750.0
1       2  Pranav        650.0
2       3    Teja          NaN
3       4     NaN        780.0